import react from "@vitejs/plugin-react";
import { defineConfig, type Plugin } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";

/**
 * Home-screen app support (normal build only): writes sw.js with this build's files to precache,
 * so the installed app opens and plays offline.
 */
function serviceWorker(): Plugin {
  return {
    name: "heist-sw",
    apply: "build",
    generateBundle(_, bundle) {
      const files = ["./", "./manifest.webmanifest", "./icons/apple-touch-icon.png", "./icons/icon-192.png", "./icons/icon-512.png", ...Object.keys(bundle).map((f) => "./" + f)];
      const version = Date.now().toString(36);
      this.emitFile({
        type: "asset",
        fileName: "sw.js",
        source: `// Generated by vite.config.ts. Precaches this build; pages load network-first, files cache-first.
const CACHE = "heist-${version}";
const FILES = ${JSON.stringify(files)};
self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", (e) => {
  const req = e.request;
  const url = new URL(req.url);
  // never cache the account API: it must always be live
  if (req.method !== "GET" || url.origin !== location.origin || url.pathname.startsWith("/api/")) return;
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req)
        .then((res) => {
          // a 502 while the server restarts must not replace the saved app, and the saved app beats it
          if (!res.ok) return caches.match("./").then((hit) => hit || res);
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put("./", copy));
          return res;
        })
        .catch(() => caches.match("./")),
    );
    return;
  }
  e.respondWith(
    caches.match(req).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
`,
      });
    },
  };
}

/** The single-file build is for sharing a link; it drops the home-screen app tags (their files aren't in it). */
function stripAppTags(): Plugin {
  return {
    name: "heist-strip-app-tags",
    transformIndexHtml: (html) => html.replace(/\s*<!-- app:start[\s\S]*?<!-- app:end -->/, ""),
  };
}

// `--mode single` builds one self-contained index.html (for sharing a playable link).
// `base: "./"` lets the normal build run from any folder, e.g. GitHub Pages at /Heist/.
export default defineConfig(({ mode }) => ({
  base: "./",
  plugins: [react(), ...(mode === "single" ? [viteSingleFile(), stripAppTags()] : [serviceWorker()])],
  build: { outDir: mode === "single" ? "dist-single" : "dist", copyPublicDir: mode !== "single" },
}));
